apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sealed-secrets
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    # Official Sealed Secrets Helm chart
    - repoURL: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: "2.19.1"

      helm:
        releaseName: sealed-secrets

        valueFiles:
          - $values/infrastructure/sealed-secrets/values.yaml

    # Our values stored in homelab-k8s
    - repoURL: https://github.com/HermannMarinho/homelab-kubernetes.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true