---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBNxJExP8qIxvgvMAWiRuHAXR7A9p3RnadsnfHo3NZBswKM2ab0HkNLpFVPN8q14Cu3VlaRCHtVM48/IMdk2sJ0KfyqRODwOF+mKz6SRBjM2mXUugyeBl9SDBTqrUH6ukHzaCf8Jw7hJy7dbZVIEWnqMfGvLZZV3dnfFjWD7wAHXWSMJLemIGItGBfRrxUa/ZgGmRqCKvkn7t4NythU7stfc8AlVNudCmytkRkqU7xCXsrjPxsoqKLwV4W867Sul0duqUBlG2JK298tguZg4+I5BAykAKnatvYiwIcDBiCz5jri/0qiRBp9leBZQWw52wFDB7dbGFYbwCz37GcTaRAPwZeATqDmyrTpeYkeUw7JUMIFP+k4eSYZIm1NDUbyqwdYH2YoFo4Uywgfa8K189kXAu7f+DWAoeZtWocTjvo/liaoXR4Xrg5c160BQjh58mQESfYGKDYjoFBPHIeJizNBPZzFhAW286uD7GSxlYd6NpZ069H+P+//7ouEQ6WxnSQ9PDyK03M8ov75Rch+u4euD3Y5f0hEFL7csWX/BH+iVKx3VT3aJQhpoefmDkDo8eCrdNoF2jUylaOpDWMGnWpP47zlD6a7JnKzcrHltxnXrM5SXi2a03rUtInfPfprs8AJoL3bDGJx3rx5vQPPhXCVO6PZnzQ7ZCrqZzGhCOmgqaqx8yE+G7xvTNlF+TwycKtlO5MNMKBjSK8YgJgYzWM/Qv9GqRagBm/f/jToET3u4V/THskXQ3qIf2lKkKKL2iHGhacaZA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
