apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: home-wildcard
  namespace: gateway

spec:
  secretName: home-wildcard-tls

  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

  dnsNames:
    - "*.home.example.com"