---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-webhook-secret
  namespace: argocd
spec:
  encryptedData:
    githubSecret: AgByM0sUkY3LqNUT1k6YHiqfbxUV2hDk6sX9wVgIuIJNTzBuDMtidVstBPEbqsghKEhKOxEhuofyClLlIsc0Bj2KSS0lSk2wuj9LZ415hC1JbumdSdwQ1YVB7tfOruP1gl8FoJajJkmdRJrLpIvta6ZtEdFV+XRgAXZRZ67dSzljjKH3fCwS45HWDBwMHeDjUG9NID7pQGlO5iBxdT4dsN3LARR37zgMfzXuPndySjcmFtYR7q4dlZgWnQuGrqwfby1xj/cCttCPZy8tHzg9qLFx15mu+qBypbLTP1r3fVoGFu3mj8LZnV2i9rzV/mDuDeZJsmV0SaMONlR10CNvXPkuGdcUc6EChVsccO8QoGBSCkV2tpHn/m6UawXTZJKgBXy6B36jBqCuBvZowKprSQjpOTgfndjUkNsxEqYFtHYXrkpge0dZenItTLfGryjyaEimANQLVNgv8Bz2Nky20/rH7lKk3VEAfnwxaNivtzzOeg7jSLlz/dyHJLz7NvP7sD0SKWvQ0Ue3K/BwaRoF4YV2Ab03LJ5l2LiKoLT4tRFYE2T/EO0wvxwqwGMzjxiEVCcDaUkLtItV/S8G0PpxuedoL3CdQPI5t40uFrKIqpqnv9xgBgQl6gFpfGSRWDNjaU7cepbNGr5yV43AShtMOJBnM0istzapIWACeg099wQs+C6vNzZ4sfmcGKamMXBC4okHbk3DxnC208B7GWB1fQT5/eNY9f3aASOwpN7bwCuNKRKPVVPkoOFX9dsoryvOzh6D3gadcnraC7YKBD88H4jg
  template:
    metadata:
      name: argocd-webhook-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
