---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rfc2136-tsig
  namespace: external-dns
spec:
  encryptedData:
    rfc2136-tsig-keyname: AgA4OZoZuhLoWZgm/Q3rvMuQRnvK5aY6adul2ciRY8mlJRvWaSeWDK+dBJjIfIXHErH6fiBdlvm54xL2YsHaO59ee0LIokM0ATpHOwTRnRtyO2/8WlBKPIgsHiZgTHh7tu4CUWmfblMs/EAQoeYjww0nZwWmg7C5JTTv6OEJKSmkqhrDvhjLTk+thLO/VblzyAiwokLuBR7vYZia+MYN2Z8Vr50sv8bo6ReDPIK/lelGZAY+UJ8LcERg17OWm738UjXMsfV3Qj/KGvdIush8fjBr8DiJb3huZtzrgRCBg7eyv0WXlraVWqDJ1UtyZ3NiwnQoL/j621GiDp8FAccyU6hH9FmVq0+DUu20buSeDTKx5nC16Mwl/rIvLwuiWh/pADN7wL/FTArxNM2YNs40pRQPrHjT3seOfvlgm2+C6fsGi7DavdK2ZcnoxibZywWZNGjOEfBTqdiIh2BRJbyDTnRI9mptp0rnnwgEDtLIgxVY6/GYKYbuhVQmCW/L0LWs3nIGmce3WSq2cBcRBF6U9BtTCexSJO52K+EMd0QFpedkPX4EwrBIaj4oj2OZCH7NkrTgNPRjBSENPIBnV4LggqA/eGSrL7n2+vZtDzRJBfzpuCjx/AfyGkhuZdGXYhhny/y0GJLT29+wTGBOG7BbdtSpBAQrA4YYJweps/k9ELA7LnfojC5PYz3l34/CXp/7WwwHD8Ez9+972RCaPXw=
    rfc2136-tsig-secret: AgCfWdx38YP509ALrp6cklccoOJMmd84l+0P0JbCHqd+z7jLVnys7IIm1dAGSuOh+veqBgBOzfUUbIzhZRjkLIvgZ1GeTX72PM8bODfXUpAvnfnUNwMYxGYpmaxjd2cftJWw9l8wQXrhRqCYB6tA4laYOEDEmCOfa1rP1FLlJqQ+h5BSEbkbc8k5p9E4Ul/LlQKW6J0uKpxq7bhfytzeI4AaI06uVJICBh7Ql+pJJJMoZ0OEGC+gQnGKxxu2vUbI2jNLDGSVSMswV7Y/73LU925HwJ1iPF+LmFadtuxkhdP4J61XoQJOsGF8VLHVYJ7pBZalVPGKapUwT+wEsoerNc5DQm8pkIMcZWdARSocuC4jq2tp/dE6iAkEdHOQn+Hv2lmLmIcQhD1TyAbKzQC9tQgzy4KbrsYik2EVSc8J33okHAVCNCkOP5E0v1LJR5dsW4Ip2bGpnInka2S92t832wxAu65ZRM8ozqDPi94xhW1epXw9xkUPXayieflbvoVSXG8dEhGV8I/oaNH+VdfvHm0MBoH1vyHlcQ16UtC0X9gPu04/yLFt0kXfQ7BqZANfgzVHsOgD459NRh1a9+4Ave//vdarKzrU95ntxewiOPtS6eHZ/BEPMcfichH6SID1vi0bvHPWSH/0Engd+Td6jg8SaoUZYXL+LnB12kNuRCTiQHeYyvW7GOSJWUB6FsOTeSRwlmKp0N8eFHa9HxypGDMhd36SFZKTdyamajt/4AkMioy4OE0gPulXvHMh1g==
  template:
    metadata:
      name: rfc2136-tsig
      namespace: external-dns
