---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rfc2136-tsig
  namespace: external-dns
spec:
  encryptedData:
    rfc2136-tsig-keyname: AgBBa0KZLDXbU7Vku+PpPrsVqhmWjlDNfP5zRnqSS2orb6303Jww98qA2IW5VYAdT6i5sgyPLGg0R72LtmcDSzKhskalHjPqjFQSCASMQIKZlMNvB6VTkcUqkobSmjErIQwn6cp3RuTDXLKYSbLVwIHF2idV539Lod7KjN4lTwdaKeGYHAlCdsxlqavpBml+YCybmaqUsLqY8pilXSFlGCGOk2MKxVkVaMmwro6Z40kM1fMTLW8NiBGQWnGH6pDUPmgf+bA5kE5qK48s/4yZ8teMG8hMag0kiLgXdTMeAKhY6xC4jz6VANo7g+Wmnb0kIYp9X79xlduyeSMBJ6Uo8upyJvrkKUKqPyOHLyko70g+XDLrEjj4fLMKSnhK0owbARVetmqVPoyHb2j+xvWZbqQRfVc9L2+9KvPFUFZBrmhLYaNl9BxBgBX1KDFLx0mJA1sc+hmow5srcg1w4LZeTkagEgNh3dnn4SSBJk0uTnOYnmUbKb4+8engkz3Pgkzjxe/ao6t1mD+FZwHLf4DijR3uruPBm/n0gpH6TiM5jADL7bkUnYJaD1D3ZjGW77zqFI3ZqCN9QQyxs0VwdqNj3d7JZKSFQD56KRkJ0QJ+H5IG3FWp1MfC4ZlBEgppRftPgi5w4gOxHU/Vwcxiog/7MaR3hcgJksvmgnI9UirXwVUccSmsAjFqGwi4QVQ5txNUv4CjB4k4i3F3CEf5b9GRFUO6AA==
    rfc2136-tsig-secret: AgAFLtezI7VS0YTG6NGPXOsk0aX83r1PSgs9/e798CvritET7FZTRyRSaJWmcl5dBl1x61Y8lbExzyJJ0d3dwxyoraC0RN16ImLXZKloQavbbYIy9K0eoBrLO+DuM30BRrDBxb39Vz6hrOuyBTUsFzsyg6oE4h+cHfyhKTLXtkcrODDyHYdxgRekoW3muSyOVIOoh2j9mOqaj+jfeEQ6j2Am9Y7fkJlXmfmzMH6eCpdriH3V/fRWBRCBfTQY991YtyyZJcrVdrnjujuYEmyMgdk7EZ8XX3whjeMhA8fRKekaCB8qB+3UUJrGVVMjwMxzBsJEVnxApcgEWIfLdyrJIa/UGxL1C+oVf6rwQOg8KQoJz2zj3y2580qcRaKNa/fC3NIynRoM8PUY/K11S9+CxPLeVY2tHw4pRd54DeBrcG5+S9khRuP4BcL45a+L2aps6roFwFwq59IvtS0SnzWifRnMPc08HbL+7rwCNqc/XNn+kU9pOpSbomb+Uw6HhzK105kTmh09pDolytLplfOwH5nLeZ6En/bvPpnGKbjlPD6sP3jcj7bOz5TzLSfeI/edAbb5y4G089ghn6DSYbcqImsj5sTJ3nd4np8Wh/soGHNESN9AEIfB7kkGh80GkuJSV2DA1cypIgGr1fHDMmNIBhzUsP9R1xSUGGNwWqO0/FGxt9/QtCsGsT3DOZPvC5yX/9zhbDXHwd0AKsUAbn8Qj3Qnu2f0tu7cE0IXSmAyvXlK8rkIqAgiBp4St70ZcQ==
  template:
    metadata:
      name: rfc2136-tsig
      namespace: external-dns
