---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rfc2136-tsig
  namespace: external-dns
spec:
  encryptedData:
    rfc2136-tsig-keyname: AgBg9UTbQCJTeUhfwZnomRdQBpR7p4izBSQfjiL7GAV0prA9tlAa2DzFJRvnfwvGu3Z2vdayfqfXYV5MRNrklSAG0Aw1n4lt0oEUPOwjyZWLF5cxe3r19R9OlN1lX+7naiVmeZ87h/qgAu5VNJfw6sNmD+VDKXdIp/7rUje9YZ3tNsbc42YvO3QzQxiODhXz0XMOK2wQO3E0ugbGfMiaShVWkRQAG0MOaosv/PJxMfh9dKyKW91HPBGsisnkD5dsFbWXLqOBl5wwi0sBOx1MCRbUokaJ+4/2DRjNE8qm16n1SE8TxzaqlV+x7F03VJPr1jQZyRzhQO2nOepiz/li5MVfAz4jReRew3gtKdym7NCMwGT5OIPYmSymf5S34odqNTg3epgb0pAvObtpSTHYO3EMP+U6ghJmp0UKI1yaQVBSOKUdvw01LBIaVqkbrrH4shdiQgrwBjqEhOZCa+j9loTrBYBFqwN9tUcDbmonf9Yu30+h1iM13Fg4MboGkCFllvpZ3u9BS9K9TtXTw6Gwx+HVeg3rdGvrNhlcZoqT21MFhUe2Nbk5ExB/QAwW+Fj9aBzjHyMn1g80iPGKC2tagvM5tQUqZLwWBJDmfL24lehumvLgx1JWUwo1h7WPj9wLlrxchxgwM476Y+Gkdoi+qAPTYZsUg8VyR8LuSo4BQ1JQUK+XzhIS9QBaciUerzMfyyOFf94EYAL9OeE0ndg3sTcRUQ==
    rfc2136-tsig-secret: AgCZX58y+FynNmKaQJps4FUum65IV5RlYDUzTz69L9WI1/uyqtx8vC7F51vvaoqdViwMx0Yj7M3Yd39axksGpnzY/YK5/l44hO1i+x9oRymltlj4f8RRtb+YRi9TgUcvrKfaANRNwwZ7AFsk2pW24f4LIgpd9MgoxGxeVEp8K9XG94EIM7D+ZF3cJZ2yadjvw63E3SICRfskrYtXOYwtX61rvlNNnUHMPanE+tPzI3SJhVgBvvgMdemWg8MW50zQiXhjp5M6acIkkxyNvD7PFp3fY41w9MKJwui4ysT2j9ivkYc+Jnttp4xJ4dsV041aWORT8D3h3FSo8/vqrB9qXXh0loxshFSPoXgInlEdYlZFpVtTw0ZM2gjgGChiW/Flvsmk/Yu+aZu93EHtQBmXPuwtakr/BTP70wxcVIa96yBM8nDnSyuqqncLdhRvYzuEu8nNExbwubM0vfBA/W7PFPQqSUK9OdDQmFDQZstixixe2KGOnFG6fKBLDxFjTm1I2s8CbAK7uF1/bzsSbiH9P0fg2gQsMpLC4A8HRiMDT7PvEfsx+4j/wc9sVOdER/97RuR+0aYP/Iw2lZQ9LsiCddn5T/Wwz3atLCKvhJUtYcEY6ytic1026gf9REwpQGSRjY9KXD1rznn6guuXiBDtxLP1ZqnTD/DKyDy3Kv79HfmJ3SkI6mJ9m3cbG23MEiMmsAA9lzaTfDQ/nxLhebJmb0klOgwwQNiq5oZPDtc=
  template:
    metadata:
      name: rfc2136-tsig
      namespace: external-dns
